name: Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codecov-tarpaulin:
    name: Generate code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
      # Note: If you need to combine the coverage info of multiple
      # feature sets, you need a `.tarpaulin.toml` config file, see
      # the link above for those docs.
      - name: Install cargo-tarpaulin
        run: "cargo install cargo-tarpaulin -f"
      - name: Run cargo-tarpaulin
        run: "cargo tarpaulin --out Xml --verbose --all-features --run-types Tests,Lib,Bins --ignore-tests"
      # Note: closed-source code needs to provide a token,
      # but open source code does not.
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
